# Tugas Penambangan Data 1
Nama : Farid Ghozali

NIM  : 210411100119


Link Colabs : https://colab.research.google.com/drive/1ucJ0bh7UYOA_uQevlc9CJ_QmudkyFN3D#scrollTo=3N1q3fIyfI20

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
netflix_titles = pd.read_csv('drive/MyDrive/Data mining/tugas/netflix_titles.csv')
netflix_titles

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

Fitur

*   show_id
*   type
* director 
* ratting

In [ ]:
netflix_titles[["show_id","type","director","rating"]].head(5)

  show_id     type         director rating
0      s1    Movie  Kirsten Johnson  PG-13
1      s2  TV Show              NaN  TV-MA
2      s3  TV Show  Julien Leclercq  TV-MA
3      s4  TV Show              NaN  TV-MA
4      s5  TV Show              NaN  TV-MA

Mengubah type dan rating
* jika movie/PG-13,jadi angka 1
* jika TV Show/TV-MA jadi angka 0

In [ ]:
# type code
type_movie = "Movie"
type_Tv = "TV Show"

# binary value
value_of_one = 1
value_of_zero = 0

def change_code_embark_to_biner(type):
    return value_of_one if type == type_movie else value_of_zero

In [ ]:
# rating code
rating_movie = "PG-13"
rating_Tv = "TV-MA"

# binary value
value_of_one = 1
value_of_zero = 0

def change_code_rating_to_biner(rating):
    return value_of_one if rating == rating_movie else value_of_zero

In [ ]:
# Update all values of 'type' series
netflix_titles["type"] = netflix_titles["type"].apply(change_code_embark_to_biner)
netflix_titles["rating"] = netflix_titles["rating"].apply(change_code_rating_to_biner)

In [ ]:
netflix_titles[["show_id","type","director","rating"]].head(5)

  show_id  type         director  rating
0      s1     1  Kirsten Johnson       1
1      s2     0              NaN       0
2      s3     0  Julien Leclercq       0
3      s4     0              NaN       0
4      s5     0              NaN       0

In [ ]:
# CONSTAN VARIABLE
DECREMENT_BY_ONE = 1
INCREMENT_BY_ONE = 1

CONTINGENCY_TABLE_VALUE = {
    "q" : (1,1),
    "r" : (1,0),
    "s" : (0,1),
    "t" : (0,0),
}

In [ ]:
def get_series(df, idx, series):
    return netflix_titles.loc[(idx), series]

In [ ]:
def get_dissimilarity_dataset(netflix_titles, series_index = [], series = []):
    first_series = get_series(netflix_titles, series_index[0], series)
    second_series = get_series(netflix_titles, series_index[1], series)
    dataset = pd.concat([first_series,second_series],axis=1)
    return dataset.T

In [ ]:
get_dissimilarity_dataset(netflix_titles, [1,2], ["type", "rating"]).T

        1  2
type    0  0
rating  0  0

In [ ]:
netflix_titles.loc[0:5, ["type", "rating"]]

   type  rating
0     1       1
1     0       0
2     0       0
3     0       0
4     0       0
5     0       0

In [ ]:
def count_contingency_value(netflix_titles, start_index = 0, last_index = 1):

    CONTINGENCY_VALUE = {
        "q" : 0,
        "r" : 0,
        "s" : 0,
        "t" : 0,
    }

    column_range = netflix_titles.shape[1]

    for column in range(column_range):
        for value in CONTINGENCY_TABLE_VALUE:
            item = list((tuple(netflix_titles.loc[(start_index):(last_index), netflix_titles.columns[column]]) == CONTINGENCY_TABLE_VALUE[value], value))
            if item[0] == True:
                if item[1] == "q":
                    CONTINGENCY_VALUE["q"] += 1
                if item[1] == "r":
                    CONTINGENCY_VALUE["r"] += 1
                if item[1] == "s":
                    CONTINGENCY_VALUE["s"] += 1
                if item[1] == "t":
                    CONTINGENCY_VALUE["t"] += 1

    return CONTINGENCY_VALUE

In [ ]:
# d(1,2)
df_1_2 = get_dissimilarity_dataset(netflix_titles, [1,2], ["type", "rating"])

In [ ]:
c_d_1_2 = count_contingency_value(df_1_2, 1, 2)

In [ ]:
# d(1,3)
df_1_3 = get_dissimilarity_dataset(netflix_titles, [1,3], ["type", "rating"])

In [ ]:
c_d_1_3 = count_contingency_value(df_1_3, 1, 3)

In [ ]:
# d(1,4)
df_1_4 = get_dissimilarity_dataset(netflix_titles, [1,4], ["type", "rating"])

In [ ]:
c_df_1_4 = count_contingency_value(df_1_4, 1, 4)

In [ ]:
df_1_2

  type rating
1    0      0
2    0      0

In [ ]:
df_1_3

  type rating
1    0      0
3    0      0

In [ ]:
df_1_4

  type rating
1    0      0
4    0      0