# TUGAS 2 PENAMBANGAN DATA 
Nama : Farid Ghozali

NIM  : 210411100119

Link Colab : https://colab.research.google.com/drive/1riMsiK6B7ieoeH2gkaJ_mjAJR8nVzpcQ#scrollTo=-sf4b6tOEP4U

**Tugas 2**

1. Carilah data yang bertipe numerik ( data klassifikasi)
2. Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*
3. Lakukan proses diskritisasi dengan basis *entropy*
4. Kumpulkan tugas dengan link github ( web statis dari jupyter book)

**Cari data**

sumber
[Data Bunga Iris](https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv)

In [ ]:
import pandas as pd
# source data
dataset_url = "https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv"

In [ ]:
# Create dataframe
n = pd.read_csv(dataset_url)

In [ ]:
# show first 15 rows
n.head(10)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa
5           5.4          3.9           1.7          0.4  Setosa
6           4.6          3.4           1.4          0.3  Setosa
7           5.0          3.4           1.5          0.2  Setosa
8           4.4          2.9           1.4          0.2  Setosa
9           4.9          3.1           1.5          0.1  Setosa

In [ ]:
# TERDIRI DARI SERI

PANJANG_SEPAL = n["sepal.length"]
LEBAR_SEPAL = n["sepal.width"]
PANJANG_PETAL = n["petal.length"]
LEBAR_PETAL = n["petal.width"]

#### Hitung Data

**Definisi discretization**

1. Proses mengubah data bertipe data *numeric* menjadi data bertipe *categorical*
2. Diskritisasi memiliki 2 pendekatan yaitu *equal-width intervals* dan *equal-frequency intervals*
3. *equal-width intervals* adalah diskritisasi dengan lebar data yang sama
4. *equal-frequency intervals* adalah diskritisasi dengan jumlah data yang sama

#### Cut

* Cut adalah sebuah metode pada library pandas untuk melakukan perhitungan interval frekuensi dengan lebar yang sama

```
# Syntax
pd.cut(series, interval, right=True, label)
```

**Lebar Sepal**

* Equal Width Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval lebar yang sama

label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True, label)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(SEPAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# kerangka data lebar sepal dan kategori sepal
n_sepal_width_ew = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ew_binning), axis=1))

In [ ]:
# ubah nama kolom
n_sepal_width_ew.columns = ["sepal.width", "category"]

In [ ]:
n_sepal_width_ew

     sepal.width       category
0            3.5          lebar
1            3.0          lebar
2            3.2          lebar
3            3.1          lebar
4            3.6          lebar
..           ...            ...
145          3.0          lebar
146          2.5  sedikit_lebar
147          3.0          lebar
148          3.4          lebar
149          3.0          lebar

[150 rows x 2 columns]

In [ ]:
# interval lebar yang sama binning dengan label
labelled_sepal_width_ew_binning

lebar            88
sedikit_lebar    47
sangat_lebar     15
Name: sepal.width, dtype: int64

In [ ]:
# interval lebar yang sama tanpa label
interval_sepal_width_ew_binning

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal.width, dtype: int64

**Lebar kelopak**

* Equal Width Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval lebar yang sama
label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True, label)
labelled_petal_width_ew_binning = petal_width_ew_binning.value_counts()
interval_petal_width_ew_binning = pd.cut(PETAL_WIDTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# kerangka data kategori kelopak-lebar dan kelopak
n_petal_width = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ew_binning), axis=1))

In [ ]:
# ubah nama kolom
n_petal_width.columns = ["petal.width", "category"]

In [ ]:
n_petal_width

     petal.width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# interval lebar yang sama dengan label
labelled_petal_width_ew_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petal.width, dtype: int64

In [ ]:
# interval lebar yang sama tanpa label
interval_petal_width_ew_binning

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal.width, dtype: int64

**Panjang Sepal**

* Equal Width Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval lebar yang sama

label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True, label)
labelled_sepal_length_ew_binning = sepal_length_ew_binning.value_counts()
interval_sepal_length_ew_binning = pd.cut(SEPAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# kerangka data lebar sepal dan kategori sepal
n_sepal_length_ew = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ew_binning), axis=1))

In [ ]:
# ubah nama kolom
n_sepal_length_ew.columns = ["sepal_length", "category"]

In [ ]:
n_sepal_length_ew

     sepal_length       category
0             5.1  sedikit_lebar
1             4.9  sedikit_lebar
2             4.7  sedikit_lebar
3             4.6  sedikit_lebar
4             5.0  sedikit_lebar
..            ...            ...
145           6.7          lebar
146           6.3          lebar
147           6.5          lebar
148           6.2          lebar
149           5.9          lebar

[150 rows x 2 columns]

In [ ]:
# interval lebar yang sama dengan label
labelled_sepal_length_ew_binning

lebar            71
sedikit_lebar    59
sangat_lebar     20
Name: sepal.length, dtype: int64

In [ ]:
# interval lebar yang sama tanpa label
interval_sepal_length_ew_binning

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal.length, dtype: int64

**Panjang kelopak**

* Equal Width Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval lebar yang sama
label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True, label)
labelled_petal_length_ew_binning = petal_length_ew_binning.value_counts()
interval_petal_length_ew_binning = pd.cut(PETAL_LENGTH_SERIES, amount_of_binning, True).value_counts()

In [ ]:
# kerangka data lebar kelopak dan kategori kelopak
n_petal_length_ew =  pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES,petal_length_ew_binning), axis=1))

In [ ]:
# ubah nama kolom
n_petal_length_ew.columns = ["petal_length", "category"]

In [ ]:
n_petal_length_ew

     petal_length       category
0             1.4  sedikit_lebar
1             1.4  sedikit_lebar
2             1.3  sedikit_lebar
3             1.5  sedikit_lebar
4             1.4  sedikit_lebar
..            ...            ...
145           5.2   sangat_lebar
146           5.0   sangat_lebar
147           5.2   sangat_lebar
148           5.4   sangat_lebar
149           5.1   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# interval lebar yang sama binning dengan label
labelled_petal_length_ew_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petal.length, dtype: int64

In [ ]:
# interval lebar yang sama keluar label
interval_petal_length_ew_binning

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal.length, dtype: int64

**Qcut**
* Qcut adalah sebuah metode pada library pandas untuk melakukan perhitungan interval frekuensi yang sama
```
# Syntax
pd.qcut(series, interval, label)
```

**Lebar Sepal**

* Equal Frequency Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval frekuensi yang sama

label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning, label)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(SEPAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# kerangka data lebar sepal dan kategori sepal
n_sepal_width_ef = pd.DataFrame(pd.concat((SEPAL_WIDTH_SERIES, sepal_width_ef_binning), axis = 1))

In [ ]:
# ubah nama kolom
n_sepal_width_ef.columns = ["sepal_width", "category"]

In [ ]:
n_sepal_width_ef

     sepal_width       category
0            3.5   sangat_lebar
1            3.0          lebar
2            3.2          lebar
3            3.1          lebar
4            3.6   sangat_lebar
..           ...            ...
145          3.0          lebar
146          2.5  sedikit_lebar
147          3.0          lebar
148          3.4   sangat_lebar
149          3.0          lebar

[150 rows x 2 columns]

In [ ]:
# interval frekuensi yang sama binning dengan label
labelled_sepal_width_ef_binning

sedikit_lebar    57
lebar            50
sangat_lebar     43
Name: sepal.width, dtype: int64

In [ ]:
# interval frekuensi yang sama keluar label
interval_sepal_width_ef_binning

(1.999, 2.9]    57
(2.9, 3.2]      50
(3.2, 4.4]      43
Name: sepal.width, dtype: int64

**Lebar kelopak**

* Equal Frequency Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval frekuensi yang sama

label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning, label)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(PETAL_WIDTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# kerangka data lebar kelopak dan kategori kelopak
n_petal_width_ef = pd.DataFrame(pd.concat((PETAL_WIDTH_SERIES, petal_width_ef_binning), axis = 1))

In [ ]:
# ubah nama kolom
n_petal_width_ef.columns = ["petal_width", "category"]

In [ ]:
n_petal_width_ef

     petal_width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# interval frekuensi yang sama binning dengan label
labelled_petal_width_ef_binning

lebar            52
sedikit_lebar    50
sangat_lebar     48
Name: petal.width, dtype: int64

In [ ]:
# interval frekuensi yang sama tanpa label
interval_petal_width_ef_binning

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal.width, dtype: int64

**Panjang Sepal**

* Equal Frequency Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval frekuensi yang sama

label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning, label)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(SEPAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# kerangka data panjang sepal dan kategori sepal
n_sepal_length_ef = pd.DataFrame(pd.concat((SEPAL_LENGTH_SERIES, sepal_length_ef_binning), axis=1))

In [ ]:
# ubah nama kolom
n_sepal_length_ef.columns = ["sepal_length", "category"]

In [ ]:
n_sepal_length_ef

     sepal_length       category
0             5.1  sedikit_lebar
1             4.9  sedikit_lebar
2             4.7  sedikit_lebar
3             4.6  sedikit_lebar
4             5.0  sedikit_lebar
..            ...            ...
145           6.7   sangat_lebar
146           6.3          lebar
147           6.5   sangat_lebar
148           6.2          lebar
149           5.9          lebar

[150 rows x 2 columns]

In [ ]:
# interval frekuensi yang sama binning dengan label
labelled_sepal_length_ef_binning

lebar            56
sedikit_lebar    52
sangat_lebar     42
Name: sepal.length, dtype: int64

In [ ]:
# interval frekuensi yang sama keluar label
interval_sepal_length_ef_binning

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal.length, dtype: int64

**Panjang kelopak**

* Equal Frequency Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# interval frekuensi yang sama

label = ["sedikit_lebar", "lebar", "sangat_lebar"]
amount_of_binning = len(label)

petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning, label)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(PETAL_LENGTH_SERIES, amount_of_binning).value_counts()

In [ ]:
# kerangka data kategori panjang kelopak dan kelopak
n_petal_length_ef = pd.DataFrame(pd.concat((PETAL_LENGTH_SERIES, petal_length_ef_binning), axis=1))

In [ ]:
# change columns name
n_petal_length_ef.columns = ["petal_length", "category"]

In [ ]:
n_petal_length_ef

     petal_length       category
0             1.4  sedikit_lebar
1             1.4  sedikit_lebar
2             1.3  sedikit_lebar
3             1.5  sedikit_lebar
4             1.4  sedikit_lebar
..            ...            ...
145           5.2   sangat_lebar
146           5.0   sangat_lebar
147           5.2   sangat_lebar
148           5.4   sangat_lebar
149           5.1   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# interval frekuensi yang sama binning dengan label
labelled_petal_length_ef_binning

lebar            54
sedikit_lebar    50
sangat_lebar     46
Name: petal.length, dtype: int64

In [ ]:
# interval frekuensi yang sama keluar label
interval_petal_length_ef_binning

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal.length, dtype: int64

**Definisi Binning berbasis entropi**

1.   Metode untuk mengelompokkan data *numeric* menjadi *categorical*
2.   Pengelompokkan dengan mencari jumlah pembagi yang terabaik
3.   Hasil pengelompokkan terbaik adalah dengan *entropy gain* yang paling besar


*  Rumus Entropy

$$
\begin{align*}
\displaystyle Entropy(S) &= \sum_{i=0}^{k} -pi \ log_{2} \ pi \\
\end{align*}
$$

**Persiapan**


*   Impor modul log2 dari *package math*
*   Ambil data yang akan digunakan


```
dataframe about petal width (Equeal Frequency Interval)
df_petal_width_ef
```

*  Tentukan label


```
labels = ["sedikit_lebar", "lebar", "sangat_lebar"]
```

In [ ]:
# modul untuk menghitung log
from math import log2

In [ ]:
# kerangka data
tujuan_data = n_petal_width_ef
tujuan_data

     petal_width       category
0            0.2  sedikit_lebar
1            0.2  sedikit_lebar
2            0.2  sedikit_lebar
3            0.2  sedikit_lebar
4            0.2  sedikit_lebar
..           ...            ...
145          2.3   sangat_lebar
146          1.9   sangat_lebar
147          2.0   sangat_lebar
148          2.3   sangat_lebar
149          1.8   sangat_lebar

[150 rows x 2 columns]

In [ ]:
# label kategori
label = ["sedikit_lebar", "lebar", "sangat_lebar"]

**Fungsi menghitung banyaknya data setiap kategori**

In [ ]:
# hitung setiap nilai berdasarkan kategori yang diberikan
def countEveryCategory(data_column, labels, column, category):
    grup = data_column.groupby(category).count()
    amount_of_every_category = []
    for label in labels:
        amount_of_every_category.append(grup.loc[label, column])
    return amount_of_every_category

**Fungsi menghitung banyaknya data setiap kategori berdasarkan nilai pembagi atau *split value* yang diberikan**

In [ ]:
# membagi data yang diberikan berdasarkan kategori dan nilai split
def split(split_value, data_column, labels, col, category):
    less_grup = data_column[data_column[col] < split_value]
    greater_grup = data_column[data_column[col] >= split_value]
    
    length_less_grup = countEveryCategory(less_grup, labels, col, category)
    length_greater_grup = countEveryCategory(greater_grup, labels, col, category)
    
    return (length_less_grup, length_greater_grup)

**Fungsi menghitung perbedaan *gain* antara entropi inisial dengan entropi nilai pembagi yang diberikan**




---
$$Gain(E_{new}) = (E_{initial}) \ - (E_{new})$$
---

In [ ]:
# membagi data yang diberikan berdasarkan kategori dan nilai split
def count_gain(inisial_entropy, new_entropy):
  return inisial_entropy - new_entropy

**Fungsi menghitung entropy**

In [ ]:
# menghitung entropi
def count_entropy(data_tujuan):
    all_prob = []
    for prob in data_tujuan:
        if (prob/sum(data_tujuan) != 0):
            all_prob.append(prob/sum(data_tujuan) * log2(prob/sum(data_tujuan)))
        else:
            all_prob.append(0)
    return -(sum(all_prob))

**Fungsi menghitung Info entropy berdasarkan nilai pembagi atau *split value* yang diberikan**


---



$$ Info_A(D) = \frac{|D_1|}{|D|} Entropy (D_1)\frac{|D_2|}{|D|}+ Entropy (D_2)$$

In [ ]:
# hitung entropi untuk nilai split yang diberikan
def info(d, data_tujuan):
    temp = []
    for value in d:
        temp.append((sum(value) / data_tujuan.shape[0]) * count_entropy(value))
    return sum(temp)

**Implementasi**


*   Hitung target *entropy*
*   Hitung target *entropy* dengan *split value*
*   Hitung *entropy gain*

In [ ]:
# entropy data target
initial_data_tujuan_entropy = count_entropy(countEveryCategory(tujuan_data, labels, tujuan_data.columns[0], tujuan_data.columns[1]))

In [ ]:
# count Entropy for the target given a split value, split value = 0.7
entropy_data_tujuan_1 = info(split(0.7, tujuan_data, labels, tujuan_data.columns[0], tujuan_data.columns[1]), tujuan_data)

In [ ]:
# perolehan informasi (target data entropi dan entropi_data_target_1)
count_gain(initial_data_tujuan_entropy, entropy_data_tujuan_1)

0.9182958340544896